"""add composite index facility_id timestamp

Revision ID: 9d43f555e369
Revises: 17c4c4d1f5d9
Create Date: 2026-04-10 00:45:37.166427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d43f555e369'
down_revision: Union[str, Sequence[str], None] = '17c4c4d1f5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_gym_occupancy_facility_id_timestamp",  # index name
        "gym_occupancy",                            # table name
        ["facility_id", "timestamp"],               # columns — order matters
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_gym_occupancy_facility_id_timestamp",
        table_name="gym_occupancy"
    )
    # ### end Alembic commands ###
