"""create gym tables

Revision ID: f7a38dbf3bdf
Revises: 
Create Date: 2026-01-14 17:41:35.766281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f7a38dbf3bdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_metadata',
    sa.Column('facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facility_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_index(op.f('ix_gym_metadata_name'), 'gym_metadata', ['name'], unique=False)
    op.create_table('gym_occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occupancy_percentage', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['gym_metadata.facility_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_occupancy_facility_id'), 'gym_occupancy', ['facility_id'], unique=False)
    op.create_index(op.f('ix_gym_occupancy_occupancy_percentage'), 'gym_occupancy', ['occupancy_percentage'], unique=False)
    op.create_index(op.f('ix_gym_occupancy_timestamp'), 'gym_occupancy', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gym_occupancy_timestamp'), table_name='gym_occupancy')
    op.drop_index(op.f('ix_gym_occupancy_occupancy_percentage'), table_name='gym_occupancy')
    op.drop_index(op.f('ix_gym_occupancy_facility_id'), table_name='gym_occupancy')
    op.drop_table('gym_occupancy')
    op.drop_index(op.f('ix_gym_metadata_name'), table_name='gym_metadata')
    op.drop_table('gym_metadata')
    # ### end Alembic commands ###
